# Generated by Django 5.0.3 on 2024-07-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(),
        ),
    ]
