# Generated by Django 5.0.3 on 2024-07-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_location"),
        ("users", "0013_merge_20240717_0927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.activity"
            ),
        ),
    ]
