# Generated by Django 5.0.3 on 2024-07-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_activity_event_activity_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="activity_id",
            new_name="activity",
        ),
    ]
