# Generated by Django 5.0.3 on 2024-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                choices=[
                    ("Football (Soccer)", "Football (Soccer)"),
                    ("Cycling", "Cycling"),
                    ("Swimming", "Swimming"),
                    ("Hiking", "Hiking"),
                    ("Tennis", "Tennis"),
                    ("Running", "Running"),
                    ("Gymnastics and Fitness", "Gymnastics and Fitness"),
                    (
                        "Winter Sports (Skiing, Snowboarding, Ice Skating)",
                        "Winter Sports (Skiing, Snowboarding, Ice Skating)",
                    ),
                    ("Handball", "Handball"),
                    ("Basketball", "Basketball"),
                    ("Yoga", "Yoga"),
                    ("Pilates", "Pilates"),
                    ("Zumba", "Zumba"),
                    ("Boxing", "Boxing"),
                    ("CrossFit", "CrossFit"),
                    ("Table Tennis", "Table Tennis"),
                    ("Horse Riding", "Horse Riding"),
                ],
                max_length=100,
            ),
        ),
    ]
