# Generated by Django 5.0.3 on 2024-07-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_rename_activity_id_event_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(),
        ),
    ]
