# Generated by Django 5.0.3 on 2024-07-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_time_alter_event_date"),
        ("events", "0004_alter_event_date"),
    ]

    operations = []
