# Generated by Django 5.0.3 on 2024-07-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_merge_20240725_1351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(default="Describe you event"),
        ),
    ]
