# Generated by Django 5.0.3 on 2024-07-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(default="Describe your event"),
        ),
    ]
