# Generated by Django 5.0.3 on 2024-07-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="hide_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="hide_telephone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="telephone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
