# Generated by Django 5.0.3 on 2024-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_preferred_activities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.jpg", upload_to="profile_images"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(),
        ),
    ]
