# Generated by Django 5.0.3 on 2024-07-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_birth_date_remove_profile_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Football (Soccer)", "Football (Soccer)"),
                            ("Cycling", "Cycling"),
                            ("Swimming", "Swimming"),
                            ("Hiking", "Hiking"),
                            ("Tennis", "Tennis"),
                            ("Running", "Running"),
                            ("Gymnastics and Fitness", "Gymnastics and Fitness"),
                            (
                                "Winter Sports (Skiing, Snowboarding, Ice Skating)",
                                "Winter Sports (Skiing, Snowboarding, Ice Skating)",
                            ),
                            ("Handball", "Handball"),
                            ("Basketball", "Basketball"),
                            ("Yoga", "Yoga"),
                            ("Pilates", "Pilates"),
                            ("Zumba", "Zumba"),
                            ("Boxing", "Boxing"),
                            ("CrossFit", "CrossFit"),
                            ("Table Tennis", "Table Tennis"),
                            ("Horse Riding", "Horse Riding"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(
                choices=[
                    ("Berlin", "Berlin"),
                    ("Hamburg", "Hamburg"),
                    ("Munich", "Munich"),
                    ("Cologne", "Cologne"),
                    ("Frankfurt", "Frankfurt"),
                    ("Stuttgart", "Stuttgart"),
                    ("Düsseldorf", "Düsseldorf"),
                    ("Dortmund", "Dortmund"),
                    ("Essen", "Essen"),
                    ("Leipzig", "Leipzig"),
                    ("Bremen", "Bremen"),
                    ("Dresden", "Dresden"),
                    ("Hanover", "Hanover"),
                    ("Nuremberg", "Nuremberg"),
                    ("Duisburg", "Duisburg"),
                    ("Bochum", "Bochum"),
                    ("Wuppertal", "Wuppertal"),
                    ("Bielefeld", "Bielefeld"),
                    ("Bonn", "Bonn"),
                    ("Münster", "Münster"),
                ],
                default="Berlin",
                max_length=50,
            ),
        ),
    ]
