# Generated by Django 5.0.3 on 2024-07-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_activity_profile_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
    ]
