# Generated by Django 5.0.3 on 2024-07-09 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("locations", "0001_initial"),
        ("users", "0006_remove_profile_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.city",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
        migrations.AddField(
            model_name="profile",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="custom_user_set", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="custom_user_set", to="auth.permission"
            ),
        ),
        migrations.CreateModel(
            name="ProfileActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Intermediate", "Intermediate"),
                            ("Beginner", "Beginner"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.activity"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_activities",
            field=models.ManyToManyField(
                blank=True, through="users.ProfileActivity", to="users.activity"
            ),
        ),
    ]
