# Generated by Django 5.0.3 on 2024-07-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_city_profile_friends_profile_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileactivity",
            name="hidden",
            field=models.BooleanField(default=True),
        ),
    ]
