# Generated by Django 5.0.3 on 2024-07-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_city_profile_friends_profile_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="preferred_activities",
        ),
        migrations.AlterUniqueTogether(
            name="profileactivity",
            unique_together={("profile", "activity")},
        ),
    ]
