# Generated by Django 5.0.3 on 2024-07-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_profileactivity_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileactivity",
            name="hidden",
        ),
    ]
