# Generated by Django 5.0.3 on 2024-07-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_profileactivity_hidden"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="profileactivity",
            unique_together={("profile", "activity")},
        ),
    ]
