# Generated by Django 5.0.3 on 2024-07-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_profileactivity_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="profileactivity",
            unique_together=set(),
        ),
    ]
