# Generated by Django 5.0.3 on 2024-07-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_profile_preferred_activities_and_more"),
        ("users", "0011_alter_profileactivity_unique_together"),
    ]

    operations = []
