# Generated by Django 5.0.3 on 2024-07-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_merge_20240716_1709"),
        ("users", "0012_merge_20240717_0823"),
    ]

    operations = []
