# Generated by Django 5.0.3 on 2024-07-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_profile_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
    ]
