# Generated by Django 5.0.6 on 2024-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Football (Soccer)", "Football (Soccer)"),
                            ("Cycling", "Cycling"),
                            ("Swimming", "Swimming"),
                            ("Hiking", "Hiking"),
                            ("Tennis", "Tennis"),
                            ("Running", "Running"),
                            ("Gymnastics and Fitness", "Gymnastics and Fitness"),
                            (
                                "Winter Sports (Skiing, Snowboarding, Ice Skating)",
                                "Winter Sports (Skiing, Snowboarding, Ice Skating)",
                            ),
                            ("Handball", "Handball"),
                            ("Basketball", "Basketball"),
                            ("Yoga", "Yoga"),
                            ("Pilates", "Pilates"),
                            ("Zumba", "Zumba"),
                            ("Boxing", "Boxing"),
                            ("CrossFit", "CrossFit"),
                            ("Table Tennis", "Table Tennis"),
                            ("Horse Riding", "Horse Riding"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Berlin", "Berlin"),
                            ("Hamburg", "Hamburg"),
                            ("Munich", "Munich"),
                            ("Cologne", "Cologne"),
                            ("Frankfurt", "Frankfurt"),
                            ("Stuttgart", "Stuttgart"),
                            ("Düsseldorf", "Düsseldorf"),
                            ("Dortmund", "Dortmund"),
                            ("Essen", "Essen"),
                            ("Leipzig", "Leipzig"),
                            ("Bremen", "Bremen"),
                            ("Dresden", "Dresden"),
                            ("Hanover", "Hanover"),
                            ("Nuremberg", "Nuremberg"),
                            ("Duisburg", "Duisburg"),
                            ("Bochum", "Bochum"),
                            ("Wuppertal", "Wuppertal"),
                            ("Bielefeld", "Bielefeld"),
                            ("Bonn", "Bonn"),
                            ("Münster", "Münster"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("about_myself", models.TextField(blank=True)),
                ("friends", models.ManyToManyField(blank=True, to="users.user")),
                (
                    "preferred_activities",
                    models.ManyToManyField(blank=True, to="users.activity"),
                ),
            ],
        ),
    ]
